- name: make certs dir
  become: yes
  file:
    path: "/home/{{ kafka_username }}/certs"
    state: directory
    mode: '0755'
    owner: "{{ kafka_username }}"
    group: "{{ kafka_username }}"

- name: make my-safe-directory dir
  become: yes
  file:
    path: "/home/{{ kafka_username }}/my-safe-directory"
    state: directory
    mode: '0755'
    owner: "{{ kafka_username }}"
    group: "{{ kafka_username }}"

- name: create ca.crt
  copy:
    src: "./temp/{{region}}/tls_cert"
    dest: "/home/{{ kafka_username }}/certs/ca.crt"
    mode: '0400'

