- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Add user to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ docker_users }}"

- name: Enable Docker service
  service:
    name: docker
    enabled: true
    state: started

- name: Pull LocalStack image
  docker_image:
    name: "{{ localstack_image }}"
    source: pull

- name: Run LocalStack container with S3
  docker_container:
    name: localstack
    image: "{{ localstack_image }}"
    state: started
    restart_policy: always
    ports:
      - "{{ localstack_port }}:4566"
    env:
      SERVICES: s3
      DEBUG: "1"
      DATA_DIR: /tmp/localstack/data
    volumes:
      - /tmp/localstack:/tmp/localstack

